/*
 * This source file was generated by the Gradle 'init' task
 */
package org.fitnessapp

import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.server.plugins.cors.routing.*
import io.ktor.server.routing.*
import io.ktor.http.*
import io.ktor.server.plugins.contentnegotiation.*
import io.ktor.serialization.kotlinx.json.*
import io.ktor.server.plugins.statuspages.*
import kotlinx.serialization.json.Json
import io.ktor.server.response.*

import org.fitnessapp.initDatabase
import org.fitnessapp.routes.userRoutes
import org.fitnessapp.routes.profileRoutes
import org.fitnessapp.routes.activityRoutes
import org.fitnessapp.routes.exericseRoutes
import org.fitnessapp.routes.muscleGroupRoutes
import org.fitnessapp.routes.categoryRoutes

fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

fun Application.module() {
    initDatabase()

    install(CORS) {
        allowHost("localhost:5173")
        allowHost("localhost:3000")
        allowHost("127.0.0.1:5173")
        allowHost("127.0.0.1:3000")

        allowHeader(HttpHeaders.ContentType)
        allowHeader(HttpHeaders.Authorization)

        allowMethod(HttpMethod.Get)
        allowMethod(HttpMethod.Post)
        allowMethod(HttpMethod.Put)
        allowMethod(HttpMethod.Delete)
        allowMethod(HttpMethod.Options)
    
        allowCredentials = true
    }

    install(ContentNegotiation) {
        json(Json {
            prettyPrint = true
            isLenient = true
            ignoreUnknownKeys = true
        })
    }

    install(StatusPages) {
        exception<Throwable> { call, cause ->
            call.respond(HttpStatusCode.InternalServerError, mapOf("error" to (cause.message ?: "Unknown error")))
        }
    }

    routing { 
        userRoutes()
        raceRoutes()
        programScheduleRoutes()
        profileRoutes()
        activityRoutes()
        muscleGroupRoutes()
        categoryRoutes()
    }

    val port = environment.config.property("ktor.deployment.port").getString()
    println("🚀 Server running at \u001B[32mhttp://localhost:$port\u001B[0m")
}
