/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import org.fitnessapp.initDatabase

fun main() {
    embeddedServer(Netty, port = 8080, module = Application::module)
        .start(wait = true)
}

fun Application.module() {
    initDatabase()

    println("Server is running 🚀")
}
